// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "avito-test-pr-service/internal/domain/models"
)

// PRInputPort is an autogenerated mock type for the PRInputPort type
type PRInputPort struct {
	mock.Mock
}

type PRInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *PRInputPort) EXPECT() *PRInputPort_Expecter {
	return &PRInputPort_Expecter{mock: &_m.Mock}
}

// CreatePR provides a mock function with given fields: ctx, prID, authorID, title
func (_m *PRInputPort) CreatePR(ctx context.Context, prID string, authorID string, title string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID, authorID, title)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID, authorID, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID, authorID, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, authorID, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRInputPort_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type PRInputPort_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - authorID string
//   - title string
func (_e *PRInputPort_Expecter) CreatePR(ctx interface{}, prID interface{}, authorID interface{}, title interface{}) *PRInputPort_CreatePR_Call {
	return &PRInputPort_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, prID, authorID, title)}
}

func (_c *PRInputPort_CreatePR_Call) Run(run func(ctx context.Context, prID string, authorID string, title string)) *PRInputPort_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *PRInputPort_CreatePR_Call) Return(_a0 *models.PullRequest, _a1 error) *PRInputPort_CreatePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRInputPort_CreatePR_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.PullRequest, error)) *PRInputPort_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPR provides a mock function with given fields: ctx, prID
func (_m *PRInputPort) GetPR(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRInputPort_GetPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPR'
type PRInputPort_GetPR_Call struct {
	*mock.Call
}

// GetPR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *PRInputPort_Expecter) GetPR(ctx interface{}, prID interface{}) *PRInputPort_GetPR_Call {
	return &PRInputPort_GetPR_Call{Call: _e.mock.On("GetPR", ctx, prID)}
}

func (_c *PRInputPort_GetPR_Call) Run(run func(ctx context.Context, prID string)) *PRInputPort_GetPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PRInputPort_GetPR_Call) Return(_a0 *models.PullRequest, _a1 error) *PRInputPort_GetPR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRInputPort_GetPR_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *PRInputPort_GetPR_Call {
	_c.Call.Return(run)
	return _c
}

// ListPRsByAssignee provides a mock function with given fields: ctx, reviewerID, status
func (_m *PRInputPort) ListPRsByAssignee(ctx context.Context, reviewerID string, status *models.PRStatus) ([]*models.PullRequest, error) {
	ret := _m.Called(ctx, reviewerID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListPRsByAssignee")
	}

	var r0 []*models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.PRStatus) ([]*models.PullRequest, error)); ok {
		return rf(ctx, reviewerID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.PRStatus) []*models.PullRequest); ok {
		r0 = rf(ctx, reviewerID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.PRStatus) error); ok {
		r1 = rf(ctx, reviewerID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRInputPort_ListPRsByAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPRsByAssignee'
type PRInputPort_ListPRsByAssignee_Call struct {
	*mock.Call
}

// ListPRsByAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID string
//   - status *models.PRStatus
func (_e *PRInputPort_Expecter) ListPRsByAssignee(ctx interface{}, reviewerID interface{}, status interface{}) *PRInputPort_ListPRsByAssignee_Call {
	return &PRInputPort_ListPRsByAssignee_Call{Call: _e.mock.On("ListPRsByAssignee", ctx, reviewerID, status)}
}

func (_c *PRInputPort_ListPRsByAssignee_Call) Run(run func(ctx context.Context, reviewerID string, status *models.PRStatus)) *PRInputPort_ListPRsByAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.PRStatus))
	})
	return _c
}

func (_c *PRInputPort_ListPRsByAssignee_Call) Return(_a0 []*models.PullRequest, _a1 error) *PRInputPort_ListPRsByAssignee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRInputPort_ListPRsByAssignee_Call) RunAndReturn(run func(context.Context, string, *models.PRStatus) ([]*models.PullRequest, error)) *PRInputPort_ListPRsByAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *PRInputPort) MergePR(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRInputPort_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type PRInputPort_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *PRInputPort_Expecter) MergePR(ctx interface{}, prID interface{}) *PRInputPort_MergePR_Call {
	return &PRInputPort_MergePR_Call{Call: _e.mock.On("MergePR", ctx, prID)}
}

func (_c *PRInputPort_MergePR_Call) Run(run func(ctx context.Context, prID string)) *PRInputPort_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PRInputPort_MergePR_Call) Return(_a0 *models.PullRequest, _a1 error) *PRInputPort_MergePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRInputPort_MergePR_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *PRInputPort_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldReviewerID
func (_m *PRInputPort) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID, oldReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, prID, oldReviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRInputPort_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type PRInputPort_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
func (_e *PRInputPort_Expecter) ReassignReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}) *PRInputPort_ReassignReviewer_Call {
	return &PRInputPort_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, prID, oldReviewerID)}
}

func (_c *PRInputPort_ReassignReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string)) *PRInputPort_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PRInputPort_ReassignReviewer_Call) Return(_a0 *models.PullRequest, _a1 error) *PRInputPort_ReassignReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRInputPort_ReassignReviewer_Call) RunAndReturn(run func(context.Context, string, string) (*models.PullRequest, error)) *PRInputPort_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewPRInputPort creates a new instance of PRInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRInputPort {
	mock := &PRInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
