// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "avito-test-pr-service/internal/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// PRRepository is an autogenerated mock type for the PRRepository type
type PRRepository struct {
	mock.Mock
}

type PRRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PRRepository) EXPECT() *PRRepository_Expecter {
	return &PRRepository_Expecter{mock: &_m.Mock}
}

// AddReviewer provides a mock function with given fields: ctx, prID, reviewerID
func (_m *PRRepository) AddReviewer(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for AddReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PRRepository_AddReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReviewer'
type PRRepository_AddReviewer_Call struct {
	*mock.Call
}

// AddReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - reviewerID uuid.UUID
func (_e *PRRepository_Expecter) AddReviewer(ctx interface{}, prID interface{}, reviewerID interface{}) *PRRepository_AddReviewer_Call {
	return &PRRepository_AddReviewer_Call{Call: _e.mock.On("AddReviewer", ctx, prID, reviewerID)}
}

func (_c *PRRepository_AddReviewer_Call) Run(run func(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID)) *PRRepository_AddReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PRRepository_AddReviewer_Call) Return(_a0 error) *PRRepository_AddReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PRRepository_AddReviewer_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *PRRepository_AddReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// CountReviewersByPRID provides a mock function with given fields: ctx, prID
func (_m *PRRepository) CountReviewersByPRID(ctx context.Context, prID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for CountReviewersByPRID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRRepository_CountReviewersByPRID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountReviewersByPRID'
type PRRepository_CountReviewersByPRID_Call struct {
	*mock.Call
}

// CountReviewersByPRID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
func (_e *PRRepository_Expecter) CountReviewersByPRID(ctx interface{}, prID interface{}) *PRRepository_CountReviewersByPRID_Call {
	return &PRRepository_CountReviewersByPRID_Call{Call: _e.mock.On("CountReviewersByPRID", ctx, prID)}
}

func (_c *PRRepository_CountReviewersByPRID_Call) Run(run func(ctx context.Context, prID uuid.UUID)) *PRRepository_CountReviewersByPRID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PRRepository_CountReviewersByPRID_Call) Return(_a0 int, _a1 error) *PRRepository_CountReviewersByPRID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRRepository_CountReviewersByPRID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *PRRepository_CountReviewersByPRID_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function with given fields: ctx, _a1
func (_m *PRRepository) CreatePR(ctx context.Context, _a1 *models.PullRequest) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequest) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PRRepository_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type PRRepository_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *models.PullRequest
func (_e *PRRepository_Expecter) CreatePR(ctx interface{}, _a1 interface{}) *PRRepository_CreatePR_Call {
	return &PRRepository_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, _a1)}
}

func (_c *PRRepository_CreatePR_Call) Run(run func(ctx context.Context, _a1 *models.PullRequest)) *PRRepository_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequest))
	})
	return _c
}

func (_c *PRRepository_CreatePR_Call) Return(_a0 error) *PRRepository_CreatePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PRRepository_CreatePR_Call) RunAndReturn(run func(context.Context, *models.PullRequest) error) *PRRepository_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRByID provides a mock function with given fields: ctx, id
func (_m *PRRepository) GetPRByID(ctx context.Context, id uuid.UUID) (*models.PullRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPRByID")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PullRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PullRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRRepository_GetPRByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRByID'
type PRRepository_GetPRByID_Call struct {
	*mock.Call
}

// GetPRByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PRRepository_Expecter) GetPRByID(ctx interface{}, id interface{}) *PRRepository_GetPRByID_Call {
	return &PRRepository_GetPRByID_Call{Call: _e.mock.On("GetPRByID", ctx, id)}
}

func (_c *PRRepository_GetPRByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PRRepository_GetPRByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PRRepository_GetPRByID_Call) Return(_a0 *models.PullRequest, _a1 error) *PRRepository_GetPRByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRRepository_GetPRByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PullRequest, error)) *PRRepository_GetPRByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPRsByReviewer provides a mock function with given fields: ctx, reviewerID, status
func (_m *PRRepository) ListPRsByReviewer(ctx context.Context, reviewerID uuid.UUID, status *models.PRStatus) ([]*models.PullRequest, error) {
	ret := _m.Called(ctx, reviewerID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListPRsByReviewer")
	}

	var r0 []*models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.PRStatus) ([]*models.PullRequest, error)); ok {
		return rf(ctx, reviewerID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.PRStatus) []*models.PullRequest); ok {
		r0 = rf(ctx, reviewerID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *models.PRStatus) error); ok {
		r1 = rf(ctx, reviewerID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRRepository_ListPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPRsByReviewer'
type PRRepository_ListPRsByReviewer_Call struct {
	*mock.Call
}

// ListPRsByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID uuid.UUID
//   - status *models.PRStatus
func (_e *PRRepository_Expecter) ListPRsByReviewer(ctx interface{}, reviewerID interface{}, status interface{}) *PRRepository_ListPRsByReviewer_Call {
	return &PRRepository_ListPRsByReviewer_Call{Call: _e.mock.On("ListPRsByReviewer", ctx, reviewerID, status)}
}

func (_c *PRRepository_ListPRsByReviewer_Call) Run(run func(ctx context.Context, reviewerID uuid.UUID, status *models.PRStatus)) *PRRepository_ListPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*models.PRStatus))
	})
	return _c
}

func (_c *PRRepository_ListPRsByReviewer_Call) Return(_a0 []*models.PullRequest, _a1 error) *PRRepository_ListPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRRepository_ListPRsByReviewer_Call) RunAndReturn(run func(context.Context, uuid.UUID, *models.PRStatus) ([]*models.PullRequest, error)) *PRRepository_ListPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// LockPRByID provides a mock function with given fields: ctx, id
func (_m *PRRepository) LockPRByID(ctx context.Context, id uuid.UUID) (*models.PullRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LockPRByID")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PullRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PullRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRRepository_LockPRByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockPRByID'
type PRRepository_LockPRByID_Call struct {
	*mock.Call
}

// LockPRByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PRRepository_Expecter) LockPRByID(ctx interface{}, id interface{}) *PRRepository_LockPRByID_Call {
	return &PRRepository_LockPRByID_Call{Call: _e.mock.On("LockPRByID", ctx, id)}
}

func (_c *PRRepository_LockPRByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PRRepository_LockPRByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PRRepository_LockPRByID_Call) Return(_a0 *models.PullRequest, _a1 error) *PRRepository_LockPRByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRRepository_LockPRByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PullRequest, error)) *PRRepository_LockPRByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReviewer provides a mock function with given fields: ctx, prID, reviewerID
func (_m *PRRepository) RemoveReviewer(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PRRepository_RemoveReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReviewer'
type PRRepository_RemoveReviewer_Call struct {
	*mock.Call
}

// RemoveReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - reviewerID uuid.UUID
func (_e *PRRepository_Expecter) RemoveReviewer(ctx interface{}, prID interface{}, reviewerID interface{}) *PRRepository_RemoveReviewer_Call {
	return &PRRepository_RemoveReviewer_Call{Call: _e.mock.On("RemoveReviewer", ctx, prID, reviewerID)}
}

func (_c *PRRepository_RemoveReviewer_Call) Run(run func(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID)) *PRRepository_RemoveReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PRRepository_RemoveReviewer_Call) Return(_a0 error) *PRRepository_RemoveReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PRRepository_RemoveReviewer_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *PRRepository_RemoveReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, prID, status, mergedAt
func (_m *PRRepository) UpdateStatus(ctx context.Context, prID uuid.UUID, status models.PRStatus, mergedAt *time.Time) error {
	ret := _m.Called(ctx, prID, status, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.PRStatus, *time.Time) error); ok {
		r0 = rf(ctx, prID, status, mergedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PRRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type PRRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - status models.PRStatus
//   - mergedAt *time.Time
func (_e *PRRepository_Expecter) UpdateStatus(ctx interface{}, prID interface{}, status interface{}, mergedAt interface{}) *PRRepository_UpdateStatus_Call {
	return &PRRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, prID, status, mergedAt)}
}

func (_c *PRRepository_UpdateStatus_Call) Run(run func(ctx context.Context, prID uuid.UUID, status models.PRStatus, mergedAt *time.Time)) *PRRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.PRStatus), args[3].(*time.Time))
	})
	return _c
}

func (_c *PRRepository_UpdateStatus_Call) Return(_a0 error) *PRRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PRRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.PRStatus, *time.Time) error) *PRRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewPRRepository creates a new instance of PRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRRepository {
	mock := &PRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
