// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReviewerSelector is an autogenerated mock type for the ReviewerSelector type
type ReviewerSelector struct {
	mock.Mock
}

type ReviewerSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *ReviewerSelector) EXPECT() *ReviewerSelector_Expecter {
	return &ReviewerSelector_Expecter{mock: &_m.Mock}
}

// Select provides a mock function with given fields: candidates, count
func (_m *ReviewerSelector) Select(candidates []string, count int) []string {
	ret := _m.Called(candidates, count)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func([]string, int) []string); ok {
		r0 = rf(candidates, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ReviewerSelector_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type ReviewerSelector_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - candidates []string
//   - count int
func (_e *ReviewerSelector_Expecter) Select(candidates interface{}, count interface{}) *ReviewerSelector_Select_Call {
	return &ReviewerSelector_Select_Call{Call: _e.mock.On("Select", candidates, count)}
}

func (_c *ReviewerSelector_Select_Call) Run(run func(candidates []string, count int)) *ReviewerSelector_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(int))
	})
	return _c
}

func (_c *ReviewerSelector_Select_Call) Return(_a0 []string) *ReviewerSelector_Select_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReviewerSelector_Select_Call) RunAndReturn(run func([]string, int) []string) *ReviewerSelector_Select_Call {
	_c.Call.Return(run)
	return _c
}

// NewReviewerSelector creates a new instance of ReviewerSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewerSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewerSelector {
	mock := &ReviewerSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
