// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "avito-test-pr-service/internal/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

type TeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamRepository) EXPECT() *TeamRepository_Expecter {
	return &TeamRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, teamID, userID
func (_m *TeamRepository) AddMember(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type TeamRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamRepository_Expecter) AddMember(ctx interface{}, teamID interface{}, userID interface{}) *TeamRepository_AddMember_Call {
	return &TeamRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, teamID, userID)}
}

func (_c *TeamRepository_AddMember_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *TeamRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_AddMember_Call) Return(_a0 error) *TeamRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamRepository_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TeamRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, _a1
func (_m *TeamRepository) CreateTeam(ctx context.Context, _a1 *models.Team) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamRepository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type TeamRepository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *models.Team
func (_e *TeamRepository_Expecter) CreateTeam(ctx interface{}, _a1 interface{}) *TeamRepository_CreateTeam_Call {
	return &TeamRepository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, _a1)}
}

func (_c *TeamRepository_CreateTeam_Call) Run(run func(ctx context.Context, _a1 *models.Team)) *TeamRepository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Team))
	})
	return _c
}

func (_c *TeamRepository_CreateTeam_Call) Return(_a0 error) *TeamRepository_CreateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamRepository_CreateTeam_Call) RunAndReturn(run func(context.Context, *models.Team) error) *TeamRepository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByID provides a mock function with given fields: ctx, id
func (_m *TeamRepository) GetTeamByID(ctx context.Context, id uuid.UUID) (*models.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByID")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Team); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetTeamByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByID'
type TeamRepository_GetTeamByID_Call struct {
	*mock.Call
}

// GetTeamByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TeamRepository_Expecter) GetTeamByID(ctx interface{}, id interface{}) *TeamRepository_GetTeamByID_Call {
	return &TeamRepository_GetTeamByID_Call{Call: _e.mock.On("GetTeamByID", ctx, id)}
}

func (_c *TeamRepository_GetTeamByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TeamRepository_GetTeamByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_GetTeamByID_Call) Return(_a0 *models.Team, _a1 error) *TeamRepository_GetTeamByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetTeamByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Team, error)) *TeamRepository_GetTeamByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByName provides a mock function with given fields: ctx, name
func (_m *TeamRepository) GetTeamByName(ctx context.Context, name string) (*models.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByName'
type TeamRepository_GetTeamByName_Call struct {
	*mock.Call
}

// GetTeamByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TeamRepository_Expecter) GetTeamByName(ctx interface{}, name interface{}) *TeamRepository_GetTeamByName_Call {
	return &TeamRepository_GetTeamByName_Call{Call: _e.mock.On("GetTeamByName", ctx, name)}
}

func (_c *TeamRepository_GetTeamByName_Call) Run(run func(ctx context.Context, name string)) *TeamRepository_GetTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamRepository_GetTeamByName_Call) Return(_a0 *models.Team, _a1 error) *TeamRepository_GetTeamByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetTeamByName_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *TeamRepository_GetTeamByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx
func (_m *TeamRepository) ListTeams(ctx context.Context) ([]*models.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []*models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type TeamRepository_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TeamRepository_Expecter) ListTeams(ctx interface{}) *TeamRepository_ListTeams_Call {
	return &TeamRepository_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx)}
}

func (_c *TeamRepository_ListTeams_Call) Run(run func(ctx context.Context)) *TeamRepository_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TeamRepository_ListTeams_Call) Return(_a0 []*models.Team, _a1 error) *TeamRepository_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_ListTeams_Call) RunAndReturn(run func(context.Context) ([]*models.Team, error)) *TeamRepository_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, teamID, userID
func (_m *TeamRepository) RemoveMember(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type TeamRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamRepository_Expecter) RemoveMember(ctx interface{}, teamID interface{}, userID interface{}) *TeamRepository_RemoveMember_Call {
	return &TeamRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, teamID, userID)}
}

func (_c *TeamRepository_RemoveMember_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *TeamRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_RemoveMember_Call) Return(_a0 error) *TeamRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TeamRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
