// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "avito-test-pr-service/internal/domain/models"

	uuid "github.com/google/uuid"
)

// TeamInputPort is an autogenerated mock type for the TeamInputPort type
type TeamInputPort struct {
	mock.Mock
}

type TeamInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamInputPort) EXPECT() *TeamInputPort_Expecter {
	return &TeamInputPort_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, teamID, userID
func (_m *TeamInputPort) AddMember(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamInputPort_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type TeamInputPort_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamInputPort_Expecter) AddMember(ctx interface{}, teamID interface{}, userID interface{}) *TeamInputPort_AddMember_Call {
	return &TeamInputPort_AddMember_Call{Call: _e.mock.On("AddMember", ctx, teamID, userID)}
}

func (_c *TeamInputPort_AddMember_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *TeamInputPort_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamInputPort_AddMember_Call) Return(_a0 error) *TeamInputPort_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamInputPort_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TeamInputPort_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, name
func (_m *TeamInputPort) CreateTeam(ctx context.Context, name string) (*models.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamInputPort_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type TeamInputPort_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TeamInputPort_Expecter) CreateTeam(ctx interface{}, name interface{}) *TeamInputPort_CreateTeam_Call {
	return &TeamInputPort_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, name)}
}

func (_c *TeamInputPort_CreateTeam_Call) Run(run func(ctx context.Context, name string)) *TeamInputPort_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamInputPort_CreateTeam_Call) Return(_a0 *models.Team, _a1 error) *TeamInputPort_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamInputPort_CreateTeam_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *TeamInputPort_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, id
func (_m *TeamInputPort) GetTeam(ctx context.Context, id uuid.UUID) (*models.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Team); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamInputPort_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type TeamInputPort_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TeamInputPort_Expecter) GetTeam(ctx interface{}, id interface{}) *TeamInputPort_GetTeam_Call {
	return &TeamInputPort_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, id)}
}

func (_c *TeamInputPort_GetTeam_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TeamInputPort_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TeamInputPort_GetTeam_Call) Return(_a0 *models.Team, _a1 error) *TeamInputPort_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamInputPort_GetTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Team, error)) *TeamInputPort_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx
func (_m *TeamInputPort) ListTeams(ctx context.Context) ([]*models.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []*models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamInputPort_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type TeamInputPort_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TeamInputPort_Expecter) ListTeams(ctx interface{}) *TeamInputPort_ListTeams_Call {
	return &TeamInputPort_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx)}
}

func (_c *TeamInputPort_ListTeams_Call) Run(run func(ctx context.Context)) *TeamInputPort_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TeamInputPort_ListTeams_Call) Return(_a0 []*models.Team, _a1 error) *TeamInputPort_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamInputPort_ListTeams_Call) RunAndReturn(run func(context.Context) ([]*models.Team, error)) *TeamInputPort_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, teamID, userID
func (_m *TeamInputPort) RemoveMember(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamInputPort_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type TeamInputPort_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamInputPort_Expecter) RemoveMember(ctx interface{}, teamID interface{}, userID interface{}) *TeamInputPort_RemoveMember_Call {
	return &TeamInputPort_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, teamID, userID)}
}

func (_c *TeamInputPort_RemoveMember_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *TeamInputPort_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamInputPort_RemoveMember_Call) Return(_a0 error) *TeamInputPort_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamInputPort_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TeamInputPort_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamInputPort creates a new instance of TeamInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamInputPort {
	mock := &TeamInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
