// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	pr "avito-test-pr-service/internal/domain/ports/output/pr"
	context "context"

	mock "github.com/stretchr/testify/mock"

	team "avito-test-pr-service/internal/domain/ports/output/team"

	user "avito-test-pr-service/internal/domain/ports/output/user"
)

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

type Transaction_Expecter struct {
	mock *mock.Mock
}

func (_m *Transaction) EXPECT() *Transaction_Expecter {
	return &Transaction_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *Transaction) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transaction_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type Transaction_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Transaction_Expecter) Commit(ctx interface{}) *Transaction_Commit_Call {
	return &Transaction_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *Transaction_Commit_Call) Run(run func(ctx context.Context)) *Transaction_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Transaction_Commit_Call) Return(_a0 error) *Transaction_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_Commit_Call) RunAndReturn(run func(context.Context) error) *Transaction_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// PRRepository provides a mock function with no fields
func (_m *Transaction) PRRepository() pr.PRRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PRRepository")
	}

	var r0 pr.PRRepository
	if rf, ok := ret.Get(0).(func() pr.PRRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pr.PRRepository)
		}
	}

	return r0
}

// Transaction_PRRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PRRepository'
type Transaction_PRRepository_Call struct {
	*mock.Call
}

// PRRepository is a helper method to define mock.On call
func (_e *Transaction_Expecter) PRRepository() *Transaction_PRRepository_Call {
	return &Transaction_PRRepository_Call{Call: _e.mock.On("PRRepository")}
}

func (_c *Transaction_PRRepository_Call) Run(run func()) *Transaction_PRRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_PRRepository_Call) Return(_a0 pr.PRRepository) *Transaction_PRRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_PRRepository_Call) RunAndReturn(run func() pr.PRRepository) *Transaction_PRRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *Transaction) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type Transaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Transaction_Expecter) Rollback(ctx interface{}) *Transaction_Rollback_Call {
	return &Transaction_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *Transaction_Rollback_Call) Run(run func(ctx context.Context)) *Transaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Transaction_Rollback_Call) Return(_a0 error) *Transaction_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_Rollback_Call) RunAndReturn(run func(context.Context) error) *Transaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// TeamRepository provides a mock function with no fields
func (_m *Transaction) TeamRepository() team.TeamRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TeamRepository")
	}

	var r0 team.TeamRepository
	if rf, ok := ret.Get(0).(func() team.TeamRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(team.TeamRepository)
		}
	}

	return r0
}

// Transaction_TeamRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamRepository'
type Transaction_TeamRepository_Call struct {
	*mock.Call
}

// TeamRepository is a helper method to define mock.On call
func (_e *Transaction_Expecter) TeamRepository() *Transaction_TeamRepository_Call {
	return &Transaction_TeamRepository_Call{Call: _e.mock.On("TeamRepository")}
}

func (_c *Transaction_TeamRepository_Call) Run(run func()) *Transaction_TeamRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_TeamRepository_Call) Return(_a0 team.TeamRepository) *Transaction_TeamRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_TeamRepository_Call) RunAndReturn(run func() team.TeamRepository) *Transaction_TeamRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function with no fields
func (_m *Transaction) UserRepository() user.UserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 user.UserRepository
	if rf, ok := ret.Get(0).(func() user.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.UserRepository)
		}
	}

	return r0
}

// Transaction_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type Transaction_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *Transaction_Expecter) UserRepository() *Transaction_UserRepository_Call {
	return &Transaction_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *Transaction_UserRepository_Call) Run(run func()) *Transaction_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_UserRepository_Call) Return(_a0 user.UserRepository) *Transaction_UserRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_UserRepository_Call) RunAndReturn(run func() user.UserRepository) *Transaction_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction creates a new instance of Transaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transaction {
	mock := &Transaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
