// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "avito-test-pr-service/internal/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, _a1
func (_m *UserRepository) CreateUser(ctx context.Context, _a1 *models.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *models.User
func (_e *UserRepository_Expecter) CreateUser(ctx interface{}, _a1 interface{}) *UserRepository_CreateUser_Call {
	return &UserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, _a1)}
}

func (_c *UserRepository_CreateUser_Call) Run(run func(ctx context.Context, _a1 *models.User)) *UserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *UserRepository_CreateUser_Call) Return(_a0 error) *UserRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *UserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamIDByUserID provides a mock function with given fields: ctx, userID
func (_m *UserRepository) GetTeamIDByUserID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamIDByUserID")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetTeamIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamIDByUserID'
type UserRepository_GetTeamIDByUserID_Call struct {
	*mock.Call
}

// GetTeamIDByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserRepository_Expecter) GetTeamIDByUserID(ctx interface{}, userID interface{}) *UserRepository_GetTeamIDByUserID_Call {
	return &UserRepository_GetTeamIDByUserID_Call{Call: _e.mock.On("GetTeamIDByUserID", ctx, userID)}
}

func (_c *UserRepository_GetTeamIDByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserRepository_GetTeamIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_GetTeamIDByUserID_Call) Return(_a0 uuid.UUID, _a1 error) *UserRepository_GetTeamIDByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetTeamIDByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (uuid.UUID, error)) *UserRepository_GetTeamIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *UserRepository_GetUserByID_Call {
	return &UserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *UserRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *UserRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.User, error)) *UserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveMembersByTeamID provides a mock function with given fields: ctx, teamID
func (_m *UserRepository) ListActiveMembersByTeamID(ctx context.Context, teamID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveMembersByTeamID")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_ListActiveMembersByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveMembersByTeamID'
type UserRepository_ListActiveMembersByTeamID_Call struct {
	*mock.Call
}

// ListActiveMembersByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *UserRepository_Expecter) ListActiveMembersByTeamID(ctx interface{}, teamID interface{}) *UserRepository_ListActiveMembersByTeamID_Call {
	return &UserRepository_ListActiveMembersByTeamID_Call{Call: _e.mock.On("ListActiveMembersByTeamID", ctx, teamID)}
}

func (_c *UserRepository_ListActiveMembersByTeamID_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *UserRepository_ListActiveMembersByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_ListActiveMembersByTeamID_Call) Return(_a0 []uuid.UUID, _a1 error) *UserRepository_ListActiveMembersByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_ListActiveMembersByTeamID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *UserRepository_ListActiveMembersByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *UserRepository) ListUsers(ctx context.Context) ([]*models.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type UserRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepository_Expecter) ListUsers(ctx interface{}) *UserRepository_ListUsers_Call {
	return &UserRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *UserRepository_ListUsers_Call) Run(run func(ctx context.Context)) *UserRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserRepository_ListUsers_Call) Return(_a0 []*models.User, _a1 error) *UserRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_ListUsers_Call) RunAndReturn(run func(context.Context) ([]*models.User, error)) *UserRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserActive provides a mock function with given fields: ctx, id, isActive
func (_m *UserRepository) UpdateUserActive(ctx context.Context, id uuid.UUID, isActive bool) error {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdateUserActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserActive'
type UserRepository_UpdateUserActive_Call struct {
	*mock.Call
}

// UpdateUserActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - isActive bool
func (_e *UserRepository_Expecter) UpdateUserActive(ctx interface{}, id interface{}, isActive interface{}) *UserRepository_UpdateUserActive_Call {
	return &UserRepository_UpdateUserActive_Call{Call: _e.mock.On("UpdateUserActive", ctx, id, isActive)}
}

func (_c *UserRepository_UpdateUserActive_Call) Run(run func(ctx context.Context, id uuid.UUID, isActive bool)) *UserRepository_UpdateUserActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *UserRepository_UpdateUserActive_Call) Return(_a0 error) *UserRepository_UpdateUserActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdateUserActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *UserRepository_UpdateUserActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserName provides a mock function with given fields: ctx, id, name
func (_m *UserRepository) UpdateUserName(ctx context.Context, id uuid.UUID, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type UserRepository_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
func (_e *UserRepository_Expecter) UpdateUserName(ctx interface{}, id interface{}, name interface{}) *UserRepository_UpdateUserName_Call {
	return &UserRepository_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, id, name)}
}

func (_c *UserRepository_UpdateUserName_Call) Run(run func(ctx context.Context, id uuid.UUID, name string)) *UserRepository_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_UpdateUserName_Call) Return(_a0 error) *UserRepository_UpdateUserName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdateUserName_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *UserRepository_UpdateUserName_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
