// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "avito-test-pr-service/internal/domain/models"

	uuid "github.com/google/uuid"
)

// UserInputPort is an autogenerated mock type for the UserInputPort type
type UserInputPort struct {
	mock.Mock
}

type UserInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInputPort) EXPECT() *UserInputPort_Expecter {
	return &UserInputPort_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, name, isActive
func (_m *UserInputPort) CreateUser(ctx context.Context, name string, isActive bool) (*models.User, error) {
	ret := _m.Called(ctx, name, isActive)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*models.User, error)); ok {
		return rf(ctx, name, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *models.User); ok {
		r0 = rf(ctx, name, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, name, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInputPort_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserInputPort_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - isActive bool
func (_e *UserInputPort_Expecter) CreateUser(ctx interface{}, name interface{}, isActive interface{}) *UserInputPort_CreateUser_Call {
	return &UserInputPort_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, name, isActive)}
}

func (_c *UserInputPort_CreateUser_Call) Run(run func(ctx context.Context, name string, isActive bool)) *UserInputPort_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *UserInputPort_CreateUser_Call) Return(_a0 *models.User, _a1 error) *UserInputPort_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInputPort_CreateUser_Call) RunAndReturn(run func(context.Context, string, bool) (*models.User, error)) *UserInputPort_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *UserInputPort) GetUser(ctx context.Context, id uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInputPort_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserInputPort_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserInputPort_Expecter) GetUser(ctx interface{}, id interface{}) *UserInputPort_GetUser_Call {
	return &UserInputPort_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *UserInputPort_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserInputPort_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserInputPort_GetUser_Call) Return(_a0 *models.User, _a1 error) *UserInputPort_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInputPort_GetUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.User, error)) *UserInputPort_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeamName provides a mock function with given fields: ctx, id
func (_m *UserInputPort) GetUserTeamName(ctx context.Context, id uuid.UUID) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeamName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInputPort_GetUserTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeamName'
type UserInputPort_GetUserTeamName_Call struct {
	*mock.Call
}

// GetUserTeamName is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserInputPort_Expecter) GetUserTeamName(ctx interface{}, id interface{}) *UserInputPort_GetUserTeamName_Call {
	return &UserInputPort_GetUserTeamName_Call{Call: _e.mock.On("GetUserTeamName", ctx, id)}
}

func (_c *UserInputPort_GetUserTeamName_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserInputPort_GetUserTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserInputPort_GetUserTeamName_Call) Return(_a0 string, _a1 error) *UserInputPort_GetUserTeamName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInputPort_GetUserTeamName_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *UserInputPort_GetUserTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembersByTeamID provides a mock function with given fields: ctx, teamID
func (_m *UserInputPort) ListMembersByTeamID(ctx context.Context, teamID uuid.UUID) ([]*models.User, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembersByTeamID")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.User, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.User); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInputPort_ListMembersByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembersByTeamID'
type UserInputPort_ListMembersByTeamID_Call struct {
	*mock.Call
}

// ListMembersByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *UserInputPort_Expecter) ListMembersByTeamID(ctx interface{}, teamID interface{}) *UserInputPort_ListMembersByTeamID_Call {
	return &UserInputPort_ListMembersByTeamID_Call{Call: _e.mock.On("ListMembersByTeamID", ctx, teamID)}
}

func (_c *UserInputPort_ListMembersByTeamID_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *UserInputPort_ListMembersByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserInputPort_ListMembersByTeamID_Call) Return(_a0 []*models.User, _a1 error) *UserInputPort_ListMembersByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInputPort_ListMembersByTeamID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*models.User, error)) *UserInputPort_ListMembersByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *UserInputPort) ListUsers(ctx context.Context) ([]*models.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInputPort_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type UserInputPort_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserInputPort_Expecter) ListUsers(ctx interface{}) *UserInputPort_ListUsers_Call {
	return &UserInputPort_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *UserInputPort_ListUsers_Call) Run(run func(ctx context.Context)) *UserInputPort_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserInputPort_ListUsers_Call) Return(_a0 []*models.User, _a1 error) *UserInputPort_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInputPort_ListUsers_Call) RunAndReturn(run func(context.Context) ([]*models.User, error)) *UserInputPort_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserActive provides a mock function with given fields: ctx, id, isActive
func (_m *UserInputPort) UpdateUserActive(ctx context.Context, id uuid.UUID, isActive bool) error {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserInputPort_UpdateUserActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserActive'
type UserInputPort_UpdateUserActive_Call struct {
	*mock.Call
}

// UpdateUserActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - isActive bool
func (_e *UserInputPort_Expecter) UpdateUserActive(ctx interface{}, id interface{}, isActive interface{}) *UserInputPort_UpdateUserActive_Call {
	return &UserInputPort_UpdateUserActive_Call{Call: _e.mock.On("UpdateUserActive", ctx, id, isActive)}
}

func (_c *UserInputPort_UpdateUserActive_Call) Run(run func(ctx context.Context, id uuid.UUID, isActive bool)) *UserInputPort_UpdateUserActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *UserInputPort_UpdateUserActive_Call) Return(_a0 error) *UserInputPort_UpdateUserActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserInputPort_UpdateUserActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *UserInputPort_UpdateUserActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserName provides a mock function with given fields: ctx, id, name
func (_m *UserInputPort) UpdateUserName(ctx context.Context, id uuid.UUID, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserInputPort_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type UserInputPort_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
func (_e *UserInputPort_Expecter) UpdateUserName(ctx interface{}, id interface{}, name interface{}) *UserInputPort_UpdateUserName_Call {
	return &UserInputPort_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, id, name)}
}

func (_c *UserInputPort_UpdateUserName_Call) Run(run func(ctx context.Context, id uuid.UUID, name string)) *UserInputPort_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *UserInputPort_UpdateUserName_Call) Return(_a0 error) *UserInputPort_UpdateUserName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserInputPort_UpdateUserName_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *UserInputPort_UpdateUserName_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserInputPort creates a new instance of UserInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInputPort {
	mock := &UserInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
