package utils

import "errors"

var (
	ErrUserNotFound            = errors.New("user not found")
	ErrUserExists              = errors.New("user already exists")
	ErrTeamNotFound            = errors.New("team not found")
	ErrTeamExists              = errors.New("team already exists")
	ErrUserNoTeam              = errors.New("user has no team")
	ErrNotFound                = errors.New("not found")
	ErrAlreadyExists           = errors.New("already exists")
	ErrInvalidArgument         = errors.New("invalid argument")
	ErrInternal                = errors.New("internal error")
	ErrInvalidJSON             = errors.New("invalid json body")
	ErrValidationFailed        = errors.New("validation failed")
	ErrInvalidUserID           = errors.New("invalid user_id")
	ErrInvalidAuthorID         = errors.New("invalid author_id")
	ErrInvalidOldUserID        = errors.New("invalid old_user_id")
	ErrInvalidPRIDFormat       = errors.New("invalid pull_request_id format: allowed [A-Za-z0-9._-], length 1..64")
	ErrPRIDRequired            = errors.New("pull_request_id is required")
	ErrAlreadyMerged           = errors.New("pr already merged")
	ErrPRExists                = errors.New("pr already exists")
	ErrPRNotFound              = errors.New("pr not found")
	ErrTooManyReviewers        = errors.New("too many reviewers")
	ErrReviewerAlreadyAssigned = errors.New("reviewer already assigned")
	ErrReviewerNotAssigned     = errors.New("reviewer not assigned")
	ErrInvalidStatus           = errors.New("invalid status")
	ErrNoReplacementCandidates = errors.New("no replacement candidates")
)
